/**
 * All user-facing copy for the app, one exported object per consuming
 * component/module. Static copy is a plain string; copy needing
 * interpolation or pluralization is a function taking named params.
 * Edit text here rather than inline in a .svelte file or src/lib/*.js.
 */
import { pluralize } from './text.js';

export const common = {
  fallbackLabelA: 'A',
  fallbackLabelB: 'B',
};

export const app = {
  demoPrompt: 'Just playing around?',
  tryDemoButton: 'Try our demo data',
  loadingDemo: 'Loading demo data…',
  demoLoadError: (message) => `Could not load demo data: ${message}`,
  systemATitle: 'System A',
  systemBTitle: 'System B',
  footerHtml: `All data remains on your device (see <a href="https://github.com/staadecker/crosswalk-generator" target="_blank" rel="noopener">source code</a>). Outputs generated by
  Crosswalk Generator
  &copy; 2026 Martin Staadecker are licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.`,
};

export const toolbar = {
  brandName: 'Crosswalk Generator',
  tagline: 'Create a mapping table between two hierarchical classification systems',
  helpTitle: 'Help — what this tool does and how to use it',
  helpAriaLabel: 'Help',
  undoTitle: 'Undo last mapping change',
  redoTitle: 'Redo last undone mapping change',
  exportButton: 'Export crosswalk (.csv)',
  exportTitle: 'Download a single CSV: one row per code, grouped by a sequential group_number',
  saveProjectButton: 'Save project',
  saveProjectTitle: 'Save systems + mappings as a reloadable JSON file',
  loadProjectButton: 'Load project',
  loadProjectTitle: 'Load a saved project JSON',
  restartButton: 'Restart',
  restartTitle: 'Remove everything and start over',
  nothingToExport: 'Nothing to export yet.',
  projectLoaded: 'Project loaded.',
  loadProjectError: (message) => `Could not load project: ${message}`,
  restarted: 'Restarted.',
  restartConfirm: 'Restart? This clears both systems and all mappings — it cannot be undone.',
  dismissHelpAriaLabel: 'Dismiss help',
  helpHeading: 'How Crosswalk Generator works',
  closeHelpAriaLabel: 'Close help',
  helpBodyHtml: `
        <p>
          Hierarchical classification systems are widely used to organize books,
          define industries, and classify patents, among other things. When two
          conflicting systems need to be used a <strong>crosswalk</strong> (also called a concordance
          table) maps codes from one to the other so data can move between them.
        </p>
        <p>
          Crosswalk Generator builds a many-to-many crosswalk between two
          hierarchical classification systems entirely in your browser — nothing
          is uploaded anywhere, and everything auto-saves to this device as you go.
        </p>
        <ol>
          <li>Upload a CSV for System A and System B (or click "${app.tryDemoButton}" to load a demo pair into both at once).</li>
          <li>Browse each system as a tree; click codes on both sides to select them.</li>
          <li>
            Click <strong>Group</strong> to combine the selected codes into one grouping, or
            flag a one-sided selection as <strong>no match</strong>.
          </li>
          <li>Export the result as a crosswalk CSV or save the project to resume later.</li>
        </ol>
        <p>
          A code already mapped elsewhere on its side is locked from a second grouping;
          clicking a not-yet-mapped parent code selects every unmapped leaf beneath it.
        </p>
        <h3>Keyboard shortcuts</h3>
        <ul>
          <li><kbd>G</kbd> — create the grouping for the current selection (same as clicking Group)</li>
        </ul>`,
  dismissCiteAriaLabel: 'Dismiss export dialog',
  citeHeading: 'Export crosswalk',
  closeCiteAriaLabel: 'Close',
  citeBodyHtml: `
          Crosswalk Generator is free to use. If you use this exported crosswalk, please
          credit <strong>Crosswalk Generator</strong> by Martin Staadecker, licensed under
          <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"
            >CC BY 4.0</a
          >.`,
  citeAgreeLabel: 'I agree to credit Crosswalk Generator when using this data.',
  cancelButton: 'Cancel',
  confirmExportButton: 'Export',
};

export const systemPanel = {
  defaultTitle: 'System',
  noReadableRows: 'That file has no readable rows.',
  parseError: (message) => `Could not parse CSV: ${message}`,
  parsing: 'Parsing…',
  uploadLabel: (title) => `Upload ${title} CSV`,
  uploadHint: 'Must include code and title columns. Level and description are optional.',
  confirmReplace: (affected) =>
    `Replacing this file will delete ${affected} ${pluralize(affected, 'mapping')} that reference it. This cannot be undone. Continue?`,
};

export const columnMapper = {
  confirmColumnsPrefix: 'Confirm the columns in',
  selectColumnsTitle: 'Select columns',
  codeColumnLabel: 'Code column',
  codeColumnHelp:
    'The unique identifier for each row, e.g. a NAICS or NACE code. Should be short and unique across the whole file.',
  titleColumnLabel: 'Title column',
  titleColumnHelp: 'A short label or name for each code — the primary text shown in the tree.',
  descColumnLabel: 'Description column',
  descColumnOptionalTag: '(optional)',
  descColumnHelp:
    'A longer, free-text description of each code. Shown only as a hover tooltip, never as the primary label.',
  selectPlaceholder: '— select —',
  nonePlaceholder: '— none —',
  configureNestingTitle: 'Configure nesting',
  dataIncludesParentsLabel: 'Data includes parent codes',
  dataIncludesParentsHelp:
    'Check this if your file already has an explicit row for every ancestor level (e.g. a row for "01" as well as "01.1" and "01.11"). Leave unchecked if it only lists the most specific codes.',
  parentsHint:
    'Parent codes are the ancestor rows above each code (e.g. "01" above "01.1"). Check this if your file already includes them — each code will nest under its own matching row. Leave unchecked (the default) to have missing ancestor codes generated automatically from each code\'s own structure (e.g. a "01" row will be created if only "01.a" and "01.b" are present).',
  levelColumnLabel: 'Level column',
  levelColumnHelp:
    'Optional. If your file has a column giving each row\'s hierarchy depth as an integer (not necessarily starting at 1 or sequential), pick it here. Leave on "Auto-detect" to infer depth from the shape of each code instead (e.g. "01" → "01.1" → "01.11", or a NAICS-style "48-49" sector range). Only available when "Data includes parent codes" is checked, since an explicit level column needs every ancestor row to already be present.',
  autoDetectOption: 'Auto-detect from code structure',
  tagLevel: 'level',
  tagCode: 'code',
  tagTitle: 'title',
  tagDescription: 'description',
  cancelButton: 'Cancel',
  buildButton: 'Build hierarchy',
};

export const mappingBar = {
  clickLeftHint: 'Click codes on the left',
  clickRightHint: 'Click codes on the right',
  relationshipAriaLabel: 'Relationship for the next mapping',
  equalTitle: 'Equal — the next mapping created will be an exact match',
  approxTitle: 'Approximately equal — the next mapping created will be an approximate match',
  removeChipAriaLabel: (code) => `Remove ${code}`,
  notePlaceholder: 'Optional note…',
  noteAriaLabel: 'Mapping note',
  markNoMatchButton: (n) => `Mark ${n} as no match`,
  groupButton: 'Group',
  groupButtonTitle: 'Group (shortcut: G)',
  linkedMessage: (keptA, keptB, skippedTotal) =>
    `Created a mapping linking ${keptA} × ${keptB} code(s).` +
    (skippedTotal ? ` (${skippedTotal} skipped — already mapped elsewhere)` : ''),
  markedNoMatchMessage: (added, skipped) =>
    `Marked ${added} ${pluralize(added, 'code')} as no match${skipped ? ` (${skipped} skipped — already mapped)` : ''}.`,
  linkHint: (nA, labelA, nB, labelB) =>
    `Creates one mapping grouping ${nA} ${labelA} ${pluralize(nA, 'code')} with ${nB} ${labelB} ${pluralize(nB, 'code')}.`,
  noMatchHint: (n) => `These ${n} code(s) have no counterpart? Mark them no match.`,
  defaultHint: 'Click one or more codes on each side to link them.',
};

export const mappingList = {
  groupingsTitle: 'Groupings',
  onlySelectedLabel: 'Only selected',
  emptyNoGroupingsPrefix: 'No groupings yet. Click codes on each side, then',
  emptyNoGroupingsSuffix: 'them.',
  emptyFiltered: 'No mappings touch the current selection.',
  sideAriaLabel: (label, name) => `${label} codes for ${name}`,
  noMatchDropHint: (label) => `— (no match) — drop a ${label} code here`,
  relTitleApprox: 'Approximately equal — click to mark as equal',
  relTitleEqual: 'Equal — click to mark as approximately equal',
  toggleRelAriaLabel: (name) => `Toggle equal/approximately-equal for ${name}`,
  removeBubbleAriaLabel: (code, name) => `Remove ${code} from ${name}`,
  addNoteTitle: 'Add a note',
  editNoteAriaLabel: (name) => `Edit note for ${name}`,
  addNoteAriaLabel: (name) => `Add a note for ${name}`,
  removeMappingTitle: 'Remove this whole mapping',
  removeMappingAriaLabel: (name) => `Remove mapping ${name}`,
  notePlaceholder: 'Add a note…',
  noteAriaLabel: (name) => `Note for ${name}`,
  skippedMessage: (n) => `${n} ${pluralize(n, 'code')} skipped — already mapped elsewhere.`,
};

export const treePanel = {
  systemLabel: (accent) => `System ${accent}`,
  datasetNameTitle: 'Dataset name — also used in exported filenames',
  datasetNameAriaLabel: 'Dataset name',
  renameDatasetTitle: 'Rename dataset',
  renameAriaLabel: (name) => `Rename ${name}`,
  replaceFileButton: 'Replace file…',
  replaceFileTitle: 'Replace this file — deletes any mappings that reference it',
  searchPlaceholder: 'Search code or title…',
  searchAriaLabel: (name) => `Search ${name}`,
  expandButton: 'Expand',
  expandTitle: 'Expand all',
  collapseButton: 'Collapse',
  collapseTitle: 'Collapse all',
  selectedCount: (n) => `${n} selected`,
  clearButton: 'Clear',
  progressAriaLabel: (name) => `${name} mapping progress`,
  progressLabel: (mapped, total) => `${mapped} / ${total} mapped`,
  warningsSummary: (n) => `${n} ${pluralize(n, 'warning')} while building hierarchy`,
  moreWarnings: (n) => `… and ${n} more.`,
  noMatchQuery: (query) => `No codes match “${query}”.`,
  noCodesToShow: 'No codes to show.',
  mappedBadgeTitle: 'Mapped',
  noMatchBadgeTitle: 'Marked as no match',
  noMatchBadgeText: '∅ no match',
};

export const fileUpload = {
  defaultLabel: 'Upload CSV',
  dropHint: 'Drag & drop or click to choose a .csv file',
};

export const hierarchy = {
  missingCode: (row) => `Row ${row}: missing code — row skipped.`,
  invalidLevel: (row, rawCode) => `Row ${row} (code "${rawCode}"): missing or non-numeric level — row skipped.`,
  duplicateCode: (row, rawCode) =>
    `Row ${row}: duplicate code "${rawCode}" — kept the first occurrence, skipped this one.`,
  noRootRows: 'No root rows detected — check that the level column is correct.',
};
