/**
 * All user-facing copy for the app, one exported object per consuming
 * component/module. Static copy is a plain string; copy needing
 * interpolation or pluralization is a function taking named params.
 * Edit text here rather than inline in a .svelte file or src/lib/*.js.
 */
import { pluralize } from './text.js';

export const common = {
  fallbackLabelA: 'System A',
  fallbackLabelB: 'System B',
};

export const app = {
  demoPrompt: 'First time here?',
  tryDemoButton: 'Try with demo data',
  loadingDemo: 'Loading demo data…',
  demoLoadError: (message) => `Could not load demo data: ${message}`,
  systemATitle: 'System A',
  systemBTitle: 'System B',
  footerHtml: `All data remains on your device (see <a href="https://github.com/staadecker/crosswalk-generator" target="_blank" rel="noopener">source code</a>). Outputs generated by
  Crosswalk Generator
  &copy; 2026 Martin Staadecker are licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.`,
};

export const toolbar = {
  brandName: 'Crosswalk Generator',
  tagline: 'Create a mapping table between two hierarchical classification systems',
  helpTitle: 'Help — what this tool does and how to use it',
  helpAriaLabel: 'Help',
  undoTitle: 'Undo last mapping change',
  redoTitle: 'Redo last undone mapping change',
  exportButton: 'Export crosswalk (.csv)',
  exportTitle: 'Download a single CSV: one row per code, grouped by a sequential group_number',
  saveProjectButton: 'Save project',
  saveProjectTitle: 'Save systems and groupings as a reloadable JSON file',
  loadProjectButton: 'Load project',
  loadProjectTitle: 'Load a saved project JSON',
  restartButton: 'Restart',
  restartTitle: 'Remove everything and start over',
  projectLoaded: 'Project loaded.',
  loadProjectError: (message) => `Could not load project: ${message}`,
  restarted: 'Restarted.',
  restartConfirm: 'Restart? Both systems and all groupings will be cleared. This cannot be undone.',
  dismissHelpAriaLabel: 'Dismiss help',
  helpHeading: 'How Crosswalk Generator works',
  closeHelpAriaLabel: 'Close help',
  helpBodyHtml: `
        <p>
          Hierarchical classification systems are widely used to, for example,
          <a href="https://en.wikipedia.org/wiki/Library_of_Congress_Classification" target="_blank" rel="noopener">organize</a>
          <a href="https://en.wikipedia.org/wiki/Dewey_Decimal_Classification" target="_blank" rel="noopener">books</a>,
          <a href="https://en.wikipedia.org/wiki/North_American_Industry_Classification_System" target="_blank" rel="noopener">define</a>
          <a href="https://en.wikipedia.org/wiki/Statistical_Classification_of_Economic_Activities_in_the_European_Community" target="_blank" rel="noopener">industries</a>,
          and <a href="https://en.wikipedia.org/wiki/International_Patent_Classification" target="_blank" rel="noopener">classify</a>
          <a href="https://en.wikipedia.org/wiki/Cooperative_Patent_Classification" target="_blank" rel="noopener">patents</a>.
          When two conflicting systems need to be used a <strong>crosswalk</strong> (also called a concordance
          table) maps codes from one to the other so data can move between them.
        </p>
        <p>
          Crosswalk Generator builds a many-to-many crosswalk between two
          hierarchical classification systems entirely in your browser — nothing
          is uploaded anywhere, and everything auto-saves to this device as you go.
        </p>
        <ol>
          <li>Upload a CSV for System A and System B (or click "${app.tryDemoButton}" to load a demo pair into both at once).</li>
          <li>Browse each system as a tree; click codes on both sides to select them.</li>
          <li>
            Click <strong>Group</strong> to combine the selected codes into one grouping, or
            flag a one-sided selection as <strong>no match</strong>.
          </li>
          <li>Export the result as a crosswalk CSV or save the project to resume later.</li>
        </ol>
        <p>
          A code already mapped elsewhere on its side is locked from a second grouping;
          clicking a not-yet-mapped parent code selects every unmapped leaf beneath it.
        </p>
        <h3>Keyboard shortcuts</h3>
        <ul>
          <li><kbd>G</kbd> — create the grouping for the current selection (same as clicking Group)</li>
        </ul>`,
  dismissCiteAriaLabel: 'Dismiss export dialog',
  citeHeading: 'Export crosswalk',
  closeCiteAriaLabel: 'Close',
  citeBodyHtml: `
          Crosswalk Generator is free to use. If you use this exported crosswalk, please
          credit <strong>Crosswalk Generator</strong> by Martin Staadecker, licensed under
          <a href="https://creativecommons.org/licenses/by/4.0/" target="_blank" rel="noopener"
            >CC BY 4.0</a
          >.`,
  citeAgreeLabel: 'I agree to credit Crosswalk Generator when using this data.',
  cancelButton: 'Cancel',
  confirmExportButton: 'Export',
};

export const systemPanel = {
  defaultTitle: 'System',
  noReadableRows: 'That file has no readable rows.',
  notCsvFile: (fileName) => `"${fileName}" is not a .csv file.`,
  parseError: (message) => `Could not parse CSV: ${message}`,
  parsing: 'Parsing…',
  uploadLabel: (title) => `Upload list of codes`,
  uploadHint: 'Must be a CSV file with one row per code and columns for the code, code name, and optionally, code description and hierarchy level.',
  confirmReplace: (affected) =>
    `Replacing this file will delete ${affected} ${pluralize(affected, 'grouping')} that reference it. This cannot be undone. Continue?`,
};

export const columnMapper = {
  selectColumnsTitle: 'Select columns',
  codeColumnLabel: 'Column containing the codes',
  titleColumnLabel: 'Column containing the code names',
  descColumnLabel: 'Column containing the code descriptions',
  descColumnOptionalTag: '(optional)',
  selectPlaceholder: '— select —',
  nonePlaceholder: '— none —',
  configureNestingTitle: 'Configure nesting',
  dataOnlyLowestLevelLabel: 'Data includes only lowest-level codes (auto-group codes)',
  onlyLowestLevelHint:
    'Uncheck this box if your data includes parent codes. For example, 1.1 is a parent of 1.1.1 and 1.1.2. If left checked, parent codes will be generated automatically.',
  levelColumnLabel: 'Column specifying the level of codes',
  autoDetectOption: 'None (auto-detect from code structure)',
  tagLevel: 'level',
  tagCode: 'code',
  tagTitle: 'name',
  tagDescription: 'description',
  cancelButton: 'Cancel',
  buildButton: 'Build hierarchy',
};

export const mappingBar = {
  clickLeftHint: 'Select codes',
  clickRightHint: 'Select codes',
  relationshipAriaLabel: 'Relationship for the next grouping',
  equalTitle: 'Equal — the next grouping created will be an exact match',
  approxTitle: 'Approximately equal — the next grouping created will be an approximate match',
  removeChipAriaLabel: (code) => `Remove ${code}`,
  notePlaceholder: 'Optional note…',
  noteAriaLabel: 'Grouping note',
  markNoMatchButton: (n) => `Mark ${n} as no match`,
  groupButton: 'Group',
  groupButtonTitle: 'Group (shortcut: G)',
};

export const mappingList = {
  groupingsTitle: 'Groupings',
  emptyNoGroupingsPrefix: 'No groupings yet. Click codes on each side, then',
  emptyNoGroupingsSuffix: 'them.',
  sideAriaLabel: (label, name) => `${label} codes for ${name}`,
  noMatchDropHint: (label) => `No match`,
  relTitleApprox: 'Approximately equal — click to mark as equal',
  relTitleEqual: 'Equal — click to mark as approximately equal',
  toggleRelAriaLabel: (name) => `Toggle equal/approximately-equal for ${name}`,
  removeBubbleAriaLabel: (code, name) => `Remove ${code} from ${name}`,
  addNoteTitle: 'Add a note',
  editNoteAriaLabel: (name) => `Edit note for ${name}`,
  addNoteAriaLabel: (name) => `Add a note for ${name}`,
  removeMappingTitle: 'Remove this whole grouping',
  removeMappingAriaLabel: (name) => `Remove grouping ${name}`,
  notePlaceholder: 'Add a note…',
  noteAriaLabel: (name) => `Note for ${name}`,
  skippedMessage: (n) => `${n} ${pluralize(n, 'code')} skipped — already grouped elsewhere.`,
};

export const treePanel = {
  systemLabel: (accent) => `System ${accent}`,
  datasetNameTitle: 'Dataset name — also used in exported filenames',
  datasetNameAriaLabel: 'Dataset name',
  renameDatasetTitle: 'Rename dataset',
  renameAriaLabel: (name) => `Rename ${name}`,
  replaceFileButton: 'Replace file…',
  replaceFileTitle: 'Replace this file — deletes any groupings that reference it',
  searchPlaceholder: 'Search code or title…',
  searchAriaLabel: (name) => `Search ${name}`,
  expandButton: 'Expand',
  expandTitle: 'Expand all',
  collapseButton: 'Collapse',
  collapseTitle: 'Collapse all',
  selectedCount: (n) => `${n} selected`,
  clearButton: 'Clear',
  progressAriaLabel: (name) => `${name} mapping progress`,
  progressLabel: (mapped, total) => `${mapped} / ${total} mapped`,
  warningsSummary: (n) => `${n} ${pluralize(n, 'warning')} while building hierarchy`,
  moreWarnings: (n) => `… and ${n} more.`,
  noMatchQuery: (query) => `No codes match “${query}”.`,
  noCodesToShow: 'No codes to show.',
  mappedBadgeTitle: 'Mapped',
  noMatchBadgeTitle: 'Marked as no match',
  noMatchBadgeText: '∅ no match',
};

export const fileUpload = {
  defaultLabel: 'Upload CSV',
};

export const hierarchy = {
  missingCode: (row) => `Row ${row}: missing code — row skipped.`,
  invalidLevel: (row, rawCode) => `Row ${row} (code "${rawCode}"): missing or non-numeric level — row skipped.`,
  duplicateCode: (row, rawCode) =>
    `Row ${row}: duplicate code "${rawCode}" — kept the first occurrence, skipped this one.`,
  noRootRows: 'No root rows detected — check that the level column is correct.',
};
