<script>
  import Toolbar from './components/Toolbar.svelte';
  import SystemPanel from './components/SystemPanel.svelte';
  import MappingBar from './components/MappingBar.svelte';
  import MappingList from './components/MappingList.svelte';
  import {
    systemA,
    systemB,
    mappings,
    selectionA,
    selectionB,
    mappingCounts,
    toggleSelection,
    clearSelection,
    addToSelection,
    hoverA,
    hoverB,
  } from './lib/stores.js';

  // Offered as one-click "try sample data" shortcuts on both sides — either side can
  // load any of them, so a user can freely mix and match which classification acts
  // as system A vs. system B.
  const SAMPLE_DATASETS = [
    { file: 'naics-sample.csv', label: 'NAICS (small sample)' },
    { file: 'nace-sample.csv', label: 'NACE (small sample)' },
    { file: '2022_NAICS_Descriptions.csv', label: 'NAICS 2022 (full, with descriptions)' },
  ];

  function linked() {
    // Per the UX decision, clear both selections after creating links / no-match.
    clearSelection(selectionA);
    clearSelection(selectionB);
  }
</script>

<div class="app">
  <Toolbar mappingCount={$mappings.length} />

  <main>
    <section class="side">
      <SystemPanel
        title="System A"
        accent="A"
        samples={SAMPLE_DATASETS}
        bind:system={$systemA}
        selected={$selectionA}
        counts={$mappingCounts.a}
        noMatchCodes={$mappingCounts.noMatchA}
        onToggle={(code) => toggleSelection(selectionA, code)}
        onClear={() => clearSelection(selectionA)}
        onHover={(code) => hoverA.set(code)}
        onSelectUnmapped={(codes) => addToSelection(selectionA, codes)}
      />
    </section>

    <section class="center">
      <MappingBar
        systemA={$systemA}
        systemB={$systemB}
        selectionA={$selectionA}
        selectionB={$selectionB}
        onLinked={linked}
        onClearA={() => clearSelection(selectionA)}
        onClearB={() => clearSelection(selectionB)}
        onRemoveA={(code) => toggleSelection(selectionA, code)}
        onRemoveB={(code) => toggleSelection(selectionB, code)}
      />
      <MappingList
        mappings={$mappings}
        systemA={$systemA}
        systemB={$systemB}
        selectionA={$selectionA}
        selectionB={$selectionB}
      />
    </section>

    <section class="side">
      <SystemPanel
        title="System B"
        accent="B"
        samples={SAMPLE_DATASETS}
        bind:system={$systemB}
        selected={$selectionB}
        counts={$mappingCounts.b}
        noMatchCodes={$mappingCounts.noMatchB}
        onToggle={(code) => toggleSelection(selectionB, code)}
        onClear={() => clearSelection(selectionB)}
        onHover={(code) => hoverB.set(code)}
        onSelectUnmapped={(codes) => addToSelection(selectionB, codes)}
      />
    </section>
  </main>

  <footer>
    All data remains on your device (see <a href="https://github.com/staadecker/crosswalk-generator" target="_blank" rel="noopener">source code</a>). Outputs generated by
  Crosswalk Generator
  &copy; 2026 Martin Staadecker are licensed under
  <a href="https://creativecommons.org/licenses/by/4.0/">CC BY 4.0</a>.
  </footer>
</div>

<style>
  .app {
    display: flex;
    flex-direction: column;
    height: 100vh;
  }
  main {
    flex: 1;
    min-height: 0;
    display: grid;
    grid-template-columns: 1fr 1.1fr 1fr;
    gap: 12px;
    padding: 12px;
  }
  section {
    min-height: 0;
    min-width: 0; /* allow grid tracks to share width instead of growing to content */
    display: flex;
    flex-direction: column;
  }
  .center {
    gap: 12px;
  }
  footer {
    padding: 8px 16px;
    font-size: 12px;
    color: var(--text-muted);
    border-top: 1px solid var(--border);
    background: var(--surface);
    text-align: center;
  }
  @media (max-width: 900px) {
    .app {
      height: auto;
      min-height: 100vh;
    }
    main {
      grid-template-columns: 1fr;
    }
    section {
      max-height: 70vh;
    }
  }
</style>
